-- cup_accessibility.lua (generated by generate_pack.py - do not hand-edit)
--
-- CUP_NAME_SET: cup name -> true, for onItemReceived to recognize a received cup
-- unlock item (worlds/mkds's own individually-named Cup item - see rules.py's
-- module docstring). TRACK_TO_CUP: track name -> its parent cup's name, so a
-- track's own GP-placement accessibility can mirror its cup's - see
-- autotracking.lua's mkds_cup_accessible/mkds_track_accessible.

CUP_NAME_SET = {
    ["Mushroom Cup"] = true,
    ["Flower Cup"] = true,
    ["Star Cup"] = true,
    ["Special Cup"] = true,
    ["Shell Cup"] = true,
    ["Banana Cup"] = true,
    ["Leaf Cup"] = true,
    ["Lightning Cup"] = true,
}

TRACK_TO_CUP = {
    ["Figure-8 Circuit"] = "Mushroom Cup",
    ["Yoshi Falls"] = "Mushroom Cup",
    ["Cheep Cheep Beach"] = "Mushroom Cup",
    ["Luigi's Mansion"] = "Mushroom Cup",
    ["Desert Hills"] = "Flower Cup",
    ["Delfino Square"] = "Flower Cup",
    ["Waluigi Pinball"] = "Flower Cup",
    ["Shroom Ridge"] = "Flower Cup",
    ["DK Pass"] = "Star Cup",
    ["Tick-Tock Clock"] = "Star Cup",
    ["Mario Circuit"] = "Star Cup",
    ["Airship Fortress"] = "Star Cup",
    ["Wario Stadium"] = "Special Cup",
    ["Peach Gardens"] = "Special Cup",
    ["Bowser's Castle"] = "Special Cup",
    ["Rainbow Road"] = "Special Cup",
    ["SNES Mario Circuit 1"] = "Shell Cup",
    ["N64 Moo Moo Farm"] = "Shell Cup",
    ["GBA Peach Circuit"] = "Shell Cup",
    ["GCN Luigi Circuit"] = "Shell Cup",
    ["SNES Donut Plains 1"] = "Banana Cup",
    ["N64 Frappe Snowland"] = "Banana Cup",
    ["GBA Bowser Castle 2"] = "Banana Cup",
    ["GCN Baby Park"] = "Banana Cup",
    ["SNES Koopa Beach 2"] = "Leaf Cup",
    ["N64 Choco Mountain"] = "Leaf Cup",
    ["GBA Luigi Circuit"] = "Leaf Cup",
    ["GCN Mushroom Bridge"] = "Leaf Cup",
    ["SNES Choco Island 2"] = "Lightning Cup",
    ["N64 Banshee Boardwalk"] = "Lightning Cup",
    ["GBA Sky Garden"] = "Lightning Cup",
    ["GCN Yoshi Circuit"] = "Lightning Cup",
}
