# generate_pack.py
#
# Regenerates items/items.json, layouts/layouts.json, and every scripts/*_to_code.lua
# lookup table directly from the real Archipelago world's own item/location names - these
# files should never be hand-edited (a real bug in an earlier version of this pack came
# from exactly that: a hand-maintained lookup table drifted from the real AP item names -
# see NOTES.md). Images (images/*.png), scripts/init.lua, scripts/autotracking.lua,
# manifest.json, and README.md are hand-written and untouched by this script.
#
# Usage: py generate_pack.py [path-to-Archipelago-checkout]
# Defaults to ../reference/Archipelago (this project's local dev checkout) if omitted.

import json
import re
import sys
from pathlib import Path

PACK_DIR = Path(__file__).parent
ap_path = Path(sys.argv[1]) if len(sys.argv) > 1 else PACK_DIR.parent / "reference" / "Archipelago"
sys.path.insert(0, str(ap_path))

from worlds.mkds.items import CHARACTERS, KARTS  # noqa: E402
from worlds.mkds.locations import (  # noqa: E402
    CUPS, TRACKS, TRACKS_BY_CUP, MISSIONS, MISSION_OBJECTIVES_BY_LEVEL, location_table,
)


def _sanitize(name: str) -> str:
    return re.sub(r"[^A-Za-z0-9]", "_", name)


def character_code(name: str) -> str:
    return f"char_{_sanitize(name)}"


def kart_code(name: str) -> str:
    return f"kart_{_sanitize(name)}"


def cup_code(name: str) -> str:
    return f"cup_{_sanitize(name)}"


def track_code(name: str) -> str:
    return f"track_{_sanitize(name)}"


def mission_code(index: int) -> str:
    level, mission = divmod(index, len(MISSION_OBJECTIVES_BY_LEVEL[0]))
    return f"mission_L{level + 1}M{mission + 1}"


def _toggle_item(name: str, img: str, code: str) -> dict:
    return {
        "type": "toggle",
        "name": name,
        "img": img,
        "disabled_img_mods": ["grey"],
        "codes": code,
    }


def _progressive_item(name: str, base_img: str, code: str) -> dict:
    return {
        "type": "progressive",
        "name": name,
        "initial_stage_idx": 0,
        "codes": code,
        "stages": [
            {"img": base_img},
            {"img": base_img.replace(".png", "_green.png")},
            {"img": base_img.replace(".png", "_grey.png")},
        ],
    }


def build_items() -> list[dict]:
    items = []
    items += [_toggle_item(name, "images/character.png", character_code(name)) for name in CHARACTERS]
    items += [_toggle_item(name, "images/kart.png", kart_code(name)) for name in KARTS]
    items += [_progressive_item(name, "images/cup.png", cup_code(name)) for name in CUPS]
    items += [_progressive_item(name, "images/track.png", track_code(name)) for name in TRACKS]
    items += [
        _progressive_item(name, "images/mission.png", mission_code(i))
        for i, name in enumerate(MISSIONS)
    ]
    return items


def _chunk(items: list, size: int) -> list[list]:
    return [items[i:i + size] for i in range(0, len(items), size)]


def build_layouts() -> dict:
    character_rows = _chunk([character_code(n) for n in CHARACTERS], 4)
    # Karts are laid out in blocks of 3 per character (KARTS is already in that order -
    # see rom_addresses.KART_ID_TO_NAME) - one row per character keeps that grouping
    # visually obvious, same idea as missions grouping by level below.
    kart_rows = _chunk([kart_code(n) for n in KARTS], 3)
    cup_rows = _chunk([cup_code(n) for n in CUPS], 4)
    track_rows = [[track_code(t) for t in TRACKS_BY_CUP[cup]] for cup in CUPS]
    mission_rows = _chunk([mission_code(i) for i in range(len(MISSIONS))], len(MISSION_OBJECTIVES_BY_LEVEL[0]))

    return {
        "layouts/characters": {"type": "itemgrid", "rows": character_rows},
        "layouts/karts": {"type": "itemgrid", "rows": kart_rows},
        "layouts/cups": {"type": "itemgrid", "rows": cup_rows},
        "layouts/time_trial": {"type": "itemgrid", "rows": track_rows},
        "layouts/missions": {"type": "itemgrid", "rows": mission_rows},
        "tracker_default": {
            "type": "array",
            "orientation": "vertical",
            "content": [
                {"type": "layout", "key": "layouts/characters"},
                {"type": "layout", "key": "layouts/karts"},
                {"type": "layout", "key": "layouts/cups"},
                {"type": "layout", "key": "layouts/time_trial"},
                {"type": "layout", "key": "layouts/missions"},
            ],
        },
    }


def _lua_key(key) -> str:
    if isinstance(key, int):
        return f"[{key}]"
    escaped = key.replace("\\", "\\\\").replace('"', '\\"')
    return f'["{escaped}"]'


def _comment_header(path: Path, header: str) -> list[str]:
    lines = [f"-- {path.name} (generated by generate_pack.py - do not hand-edit)", "--"]
    lines += [f"-- {line}" for line in header.splitlines()]
    lines.append("")
    return lines


def _write_lua_table(path: Path, table_name: str, mapping: dict, header: str) -> None:
    lines = _comment_header(path, header) + [f"{table_name} = {{"]
    for key, value in mapping.items():
        lines.append(f"    {_lua_key(key)} = \"{value}\",")
    lines.append("}")
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def _write_lua_set(path: Path, table_name: str, keys, header: str) -> None:
    lines = _comment_header(path, header) + [f"{table_name} = {{"]
    for key in keys:
        lines.append(f"    {_lua_key(key)} = true,")
    lines.append("}")
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    items = build_items()
    (PACK_DIR / "items" / "items.json").write_text(json.dumps(items, indent=2) + "\n", encoding="utf-8")

    layouts = build_layouts()
    (PACK_DIR / "layouts" / "layouts.json").write_text(json.dumps(layouts, indent=2) + "\n", encoding="utf-8")

    # ITEM_NAME_TO_CODE: keyed by the real, BARE AP item name (as received via
    # Archipelago:AddItemHandler's item_name argument) - NOT the location-suffixed name.
    # A real bug in an earlier hand-maintained version of this pack used the wrong
    # (location) name here for tracks/missions - see NOTES.md.
    item_name_to_code = {}
    for name in CHARACTERS:
        item_name_to_code[name] = character_code(name)
    for name in KARTS:
        item_name_to_code[name] = kart_code(name)
    for name in CUPS:
        item_name_to_code[name] = cup_code(name)
    for name in TRACKS:
        item_name_to_code[name] = track_code(name)
    for i, name in enumerate(MISSIONS):
        item_name_to_code[name] = mission_code(i)
    _write_lua_table(
        PACK_DIR / "scripts" / "item_name_to_code.lua", "ITEM_NAME_TO_CODE", item_name_to_code,
        "Maps a real AP item name (as received via Archipelago:AddItemHandler's item_name\n"
        "argument) to this pack's tracker item code.",
    )

    # LOCATION_NAME_TO_CODE: cup/track/mission LOCATION names -> the SAME code as their
    # corresponding item (deliberately not a separate namespace) - this is what lets
    # AddLocationHandler advance the right progressive item to its "completed" stage.
    # Characters/Karts have no tracked locations (no completion concept - see
    # items/items.json, both are simple toggles).
    location_name_to_code = {}
    for name in CUPS:
        location_name_to_code[f"{name} - Win"] = cup_code(name)
    for name in TRACKS:
        location_name_to_code[f"{name} - Staff Ghost Beaten"] = track_code(name)
    for i, name in enumerate(MISSIONS):
        location_name_to_code[f"{name} - Clear"] = mission_code(i)
    _write_lua_table(
        PACK_DIR / "scripts" / "location_name_to_code.lua", "LOCATION_NAME_TO_CODE", location_name_to_code,
        "Maps a tracked AP location name (as received via Archipelago:AddLocationHandler's\n"
        "location_name argument) to this pack's tracker item code (same code as the\n"
        "matching item - see item_name_to_code.lua).",
    )

    # LOCATION_ID_TO_CODE: same mapping, keyed by the location's numeric AP id - used to
    # resync already-checked locations after a reconnect via Archipelago.CheckedLocations
    # (an array of ids, not names).
    location_id_to_code = {}
    for name, code in location_name_to_code.items():
        location_id_to_code[location_table[name].code] = code
    _write_lua_table(
        PACK_DIR / "scripts" / "location_id_to_code.lua", "LOCATION_ID_TO_CODE", location_id_to_code,
        "Same mapping as location_name_to_code.lua, keyed by the location's numeric AP id -\n"
        "used to resync Archipelago.CheckedLocations (an array of ids) after a reconnect.",
    )

    # PROGRESSIVE_ITEM_CODES: which codes are 3-stage progressive items (cups/tracks/
    # missions) rather than simple 2-state toggles (characters/karts) - tells
    # autotracking.lua whether to set .CurrentStage or .Active.
    progressive_codes = (
        [cup_code(n) for n in CUPS] + [track_code(n) for n in TRACKS]
        + [mission_code(i) for i in range(len(MISSIONS))]
    )
    _write_lua_set(
        PACK_DIR / "scripts" / "progressive_item_codes.lua", "PROGRESSIVE_ITEM_CODES", progressive_codes,
        "Which tracker item codes are 3-stage progressive items (Cups/Tracks/Missions)\n"
        "rather than simple 2-state toggles (Characters/Karts) - tells autotracking.lua\n"
        "whether to set .CurrentStage or .Active.",
    )

    location_count = sum(1 for name in location_name_to_code)
    print(
        f"Wrote {len(items)} items ({len(CHARACTERS)} characters, {len(KARTS)} karts, "
        f"{len(CUPS)} cups, {len(TRACKS)} tracks, {len(MISSIONS)} missions), "
        f"{len(item_name_to_code)} item codes, {location_count} location codes "
        f"({len(progressive_codes)} progressive)."
    )


if __name__ == "__main__":
    main()
